### ISSUE TITLE
Is U17 74HCT139 or 74HCT138?

### ISSUE THREAD

**Issue by A-Small-Mice** [hkzlab/ISA_EMS_4Mb#1]
U17 is 74HCT139 In the BoM, but 74HCT138 On the PCB.

Which one is correct?

**Comment by hkzlab** [comment]
![isa_ems](https://user-images.githubusercontent.com/603354/200118133-34b2edb7-ff73-4c37-b6da-b7ebce3dc37c.jpg)
I can't find the '139 on the schematic, on the drawing of the pcb or on an actual board.
Where have you seen it?

Correct one is '138 btw.

**Comment by hkzlab** [comment]
![isa_ems](https://user-images.githubusercontent.com/603354/200118212-8ceef1cd-52d4-4e4a-8a4f-6e3ef7d54d5e.jpg)
Ah I read the original comment where it said that the '139 was on the board. Was perplexed not to find it on my boards.

Correct chip is the '138. I will update the BoM.

**Comment by hkzlab** [comment]
you can generally trust the board itself more, unless I make a special note on the README regarding a bug.
I usually write the BoMs as a last thing and half-asleep... 
Fixed. Closing.

**Comment by A-Small-Mice** [comment]
Thank you very much, hkzlab.
