### ISSUE TITLE
Any switch for more page frames than 64 KB?

### ISSUE THREAD

**Issue by A-Small-Mice** [hkzlab/ISA_EMS_4Mb#3]
I know that you modified the LTEMM driver. It seems that the driver has no option for page frame size. It is always fixed at 64 KB, but I sometimes need 128 KB. Is there a way for having 128 KB? If possible, I can use this card for UMB as well.

**Comment by hkzlab** [comment]
Not with the card as it is. If you check the schematics, You'll see that the address decoding hardware works with a window size of 64kb.
You'd have to redesign both card and driver.
